<?php
/**
 * ============================================================
 *  RavenWarp :: includes/uploads.php
 * ------------------------------------------------------------
 *  Secure image upload handling for avatars and banners.
 *
 *  SECURITY NOTES:
 *   - We validate the file's actual content (via getimagesize())
 *     rather than trusting its extension or client-reported MIME
 *     type, which are trivially spoofable.
 *   - We RE-ENCODE every uploaded image through GD before saving
 *     it. This strips any non-image bytes an attacker might have
 *     appended to a crafted "image" file (a classic polyglot
 *     upload trick) and guarantees what lands on disk is genuinely
 *     a flat raster image, not a disguised script.
 *   - The output filename is always generated by us
 *     (avatar.<ext> / banner.<ext>) — the user's original
 *     filename is never used for anything, closing the door on
 *     path traversal or double-extension tricks.
 * ============================================================
 */

if (!defined('RAVENWARP_APP')) {
    http_response_code(403);
    die('Direct access is not permitted.');
}

const RW_MAX_IMAGE_BYTES = 3 * 1024 * 1024; // 3 MB
const RW_ALLOWED_IMAGE_TYPES = [
    IMAGETYPE_JPEG => 'jpg',
    IMAGETYPE_PNG  => 'png',
    IMAGETYPE_WEBP => 'webp',
];

/**
 * Handles one uploaded image (from $_FILES['field_name']),
 * validates it thoroughly, re-encodes it, and saves it into
 * the given target directory as "<baseName>.<ext>".
 *
 * @param array  $fileArray   The relevant $_FILES['x'] sub-array.
 * @param string $targetDir   Absolute directory path to save into (must already exist).
 * @param string $baseName    Filename without extension, e.g. "avatar" or "banner".
 *
 * @return string|null Relative path (for DB storage) on success, null if no file was uploaded.
 * @throws RuntimeException on any validation failure — callers should catch and
 *                           turn this into a user-facing error message.
 */
function rw_handle_image_upload(array $fileArray, string $targetDir, string $baseName): ?string
{
    // No file selected is fine — avatars/banners are optional.
    if (!isset($fileArray['error']) || $fileArray['error'] === UPLOAD_ERR_NO_FILE) {
        return null;
    }

    if ($fileArray['error'] !== UPLOAD_ERR_OK) {
        throw new RuntimeException('The image upload failed. Please try a different file.');
    }

    if (!is_uploaded_file($fileArray['tmp_name'])) {
        throw new RuntimeException('Invalid upload.');
    }

    if ($fileArray['size'] > RW_MAX_IMAGE_BYTES) {
        throw new RuntimeException('Images must be 3MB or smaller.');
    }

    // Inspect the ACTUAL file content — never trust the extension or client MIME type.
    $imageInfo = @getimagesize($fileArray['tmp_name']);
    if ($imageInfo === false || !isset(RW_ALLOWED_IMAGE_TYPES[$imageInfo[2]])) {
        throw new RuntimeException('Please upload a valid JPG, PNG, or WEBP image.');
    }

    $extension = RW_ALLOWED_IMAGE_TYPES[$imageInfo[2]];
    $destination = rtrim($targetDir, '/') . '/' . $baseName . '.' . $extension;

    // Re-encode through GD — strips anything appended to the file beyond valid image
    // data, and guarantees the bytes on disk are a genuine, flat raster image.
    $sourceImage = match ($imageInfo[2]) {
        IMAGETYPE_JPEG => imagecreatefromjpeg($fileArray['tmp_name']),
        IMAGETYPE_PNG  => imagecreatefrompng($fileArray['tmp_name']),
        IMAGETYPE_WEBP => imagecreatefromwebp($fileArray['tmp_name']),
        default        => false,
    };

    if ($sourceImage === false) {
        throw new RuntimeException('The image file appears to be corrupted.');
    }

    // Flatten transparency onto white for JPEG (JPEG has no alpha channel).
    if ($extension === 'jpg') {
        imageinterlace($sourceImage, true);
    }

    $saved = match ($extension) {
        'jpg'  => imagejpeg($sourceImage, $destination, 88),
        'png'  => imagepng($sourceImage, $destination, 6),
        'webp' => imagewebp($sourceImage, $destination, 88),
        default => false,
    };

    imagedestroy($sourceImage);

    if (!$saved) {
        throw new RuntimeException('We couldn\'t save the uploaded image. Please try again.');
    }

    // Lock down permissions — readable by the web server, not executable.
    @chmod($destination, 0644);

    return $destination;
}

/**
 * Creates a user's avatar + banner directories if they don't
 * already exist. Called once at registration time.
 *
 * @return array{avatar_dir: string, banner_dir: string} Absolute paths.
 */
function rw_ensure_user_media_dirs(string $slug): array
{
    $avatarDir = __DIR__ . '/../users/images/avatars/' . $slug;
    $bannerDir = __DIR__ . '/../users/images/banners/' . $slug;

    foreach ([$avatarDir, $bannerDir] as $dir) {
        if (!is_dir($dir)) {
            if (!mkdir($dir, 0755, true) && !is_dir($dir)) {
                throw new RuntimeException('Could not create storage directory for this account.');
            }
        }
    }

    return ['avatar_dir' => $avatarDir, 'banner_dir' => $bannerDir];
}